In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("../data/heart_disease.csv")
Train = pd.read_csv("../data/Train.csv")
Test = pd.read_csv("../data/Test.csv")

In [5]:

Train

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,54,0,1,120,237,0,0,150,1,1.5,1,1
1,55,0,0,120,0,0,2,92,1,0.3,0,1
2,53,0,1,130,246,1,1,173,1,0.0,0,0
3,54,1,2,150,230,0,0,130,1,0.0,0,0
4,55,0,0,140,229,0,0,110,1,0.5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
610,54,1,1,108,267,0,1,167,1,0.0,0,0
611,52,0,0,120,182,0,0,150,1,0.0,1,1
612,63,0,0,140,187,0,1,144,1,4.0,0,1
613,39,0,2,120,200,0,0,160,1,1.0,1,0
614,41,1,2,110,250,0,2,142,1,0.0,0,0